package battleship.gameobjects;

import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import battleship.EventManager;
/**
 * 
 * @author Obi
 * @author Amec
 *
 */
public abstract class GameObject
{
	public Rectangle mBounds = new Rectangle(); //the bounds of the object
	public String mName = ""; //name, used to identify
	protected EventManager mGameObjEventMgr;
	
	/**
	 * Default constructor
	 */
	public GameObject()
	{
		
	}
	
	/**
	 * Constructor to use if defining the name and bounds
	 * @param name The name of the object
	 * @param bounds The bounds of the object
	 */
	public GameObject(String name, Rectangle bounds)
	{
		this.mName = name;
		this.mBounds = bounds;
	}
	
	/**
	 * static method to load images easily
	 * @param path The path to the image
	 * @return BufferedImage
	 */
	public static BufferedImage loadImage(String path)
	{
		BufferedImage tempImage = null;
		try
		{
			tempImage = ImageIO.read(new File(path));
		}
		catch (IOException e)
		{
			System.out.println("Unable to load \"" + path + "\"");
			tempImage = new BufferedImage(1, 1, BufferedImage.OPAQUE);
		}
		return tempImage;
	}
	
	
	public abstract void update();
	
	/**
	 * renders graphics to img
	 * NOTE: Sometimes it is faster to draw primitives (circles etc)
	 * DIRECTLY to the double buffer
	 */
	public abstract void render();
	
	/**
	 * paints to double buffer
	 * @param g The double buffer
	 */
	public abstract void paint(Graphics g);
	
	/**
	 * catches events
	 * @param em
	 */
	public abstract void pumpEvents(EventManager em);
	
	/**
	 * sends events generated by GO to the state, and then to 'em' in FSM
	 * @return EventMagager object
	 */
	public abstract EventManager getEvents();
}