package battleship.gameobjects;

import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import battleship.EventManager;

public abstract class GameObject
{
	public Rectangle r = new Rectangle(); //the bounds of the object
	public String name = ""; //name, used to identify
	protected EventManager goem;
	
	public GameObject()
	{
		
	}
	
	public GameObject(String name, Rectangle r)
	{
		this.name = name;
		this.r = r;
	}
	
	public static BufferedImage loadImage(String path)
	{
		BufferedImage b = null;
		try
		{
			b = ImageIO.read(new File(path));
		}
		catch (IOException e)
		{
			System.out.println("Unable to load \"" + path + "\"");
			b = new BufferedImage(1, 1, BufferedImage.OPAQUE);
		}
		return b;
	}
	
	public abstract void update();
	
	//renders graphics to img
	public abstract void render();
	//NOTE: Sometimes it is faster to draw primitives (circles etc)
	//DIRECTLY to the double buffer
	
	//paints to double buffer 
	public abstract void paint(Graphics g);
	
	//catches events
	public abstract void pumpEvents(EventManager em);
	
	//sends events generated by GO to the state, and then to 'em' in FSM
	public abstract EventManager getEvents();
}